apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: java-demo-hpa
  namespace: reviews
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: java-demo
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
